CREATE SEQUENCE tripcom_flights_KIX_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tripcom_flights_HKG_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tripcom_flights_SIN_seq START WITH 1 INCREMENT BY 1;
